export default {
  marquee: 'marquee',
  zpattern: 'zpattern',
  iconblock: 'iconblock',
  aside: 'aside',
  masonry: 'masonry',
  accordion: 'accordion',
  merchblock: 'merchblock',
  spacer: 'spacer',
  text: 'text',
  cards: 'cards',
  faas: 'form',
  carousel: 'carousel',
  longText: 'longtext',
  gradientLine: 'gradientline',
  iconLibrary: 'iconlibrary',
  textMarquee: 'textmarquee',
  planAndPricing: 'planndpricing',
  columnLibrary: 'collibrary',
  zTileContent: 'ztilecontent',
  promoColumn: 'promocols',
  table: 'table',
  image: 'image',
};
